# Generated by Django 5.0.3 on 2024-06-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
    ]
