# Generated by Django 5.0.3 on 2024-06-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0007_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
