# Generated by Django 5.0.3 on 2024-06-09 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0009_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_delivery', to='restaurent.restaurant'),
        ),
    ]
