# Generated by Django 5.0.3 on 2024-06-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0010_delivery_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
