# Generated by Django 5.0.3 on 2024-06-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0011_remove_delivery_delivery_time_delivery_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='restaurant_name',
        ),
    ]
