# Generated by Django 5.0.3 on 2024-06-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0013_delivery_id_payment_id_alter_delivery_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
